### ISSUE TITLE
SHOP_STORE: unbound variable

### ISSUE THREAD

**Issue by dominikx96** [Shopify/lighthouse-ci-action#11]
During action start the action fails.

Output:

```
==============================
9: Configuring shopify CLI
10: /entrypoint.sh: line 98: SHOP_STORE: unbound variable
```

Also, instruction from: [lighthouse-ci](https://shopify.dev/themes/tools/lighthouse-ci) seems to be out of date).

`on: [push]` - doesn't work

`on: push` - correct format from: [treosh/lighthouse-ci-action](https://github.com/treosh/lighthouse-ci-action)

**Comment by simon-bd** [comment]
@colinloretz did you find a solution?

**Comment by damiankrzyz** [comment]
@simon-bd @colinloretz try adding Repository secrets 
![Screenshot 2023-03-14 at 21 47 19](https://user-images.githubusercontent.com/79311645/225147839-ec55224d-e639-4075-8c8b-bc65d4067e53.png)

**Comment by michaelburtonray** [comment]
> ```
>         uses: shopify/lighthouse-ci-action@v1
>         with:
>           store: ${{ secrets.SHOP_STORE }}
> ```
> 
> This require the `SHOP_STORE` secret to be set, as per screenshot above.

is SHOP_STORE `examplestore` or `examplestore.myshopify.com` ?
