### ISSUE TITLE
Error 401 - Custom App authentication

### ISSUE THREAD

**Issue by dani-vessi** [Shopify/lighthouse-ci-action#34]
I'm getting this error and can't quite figure what's wrong. 

<img width="444" alt="image" src="https://user-images.githubusercontent.com/96259381/154956312-ceb1de63-77e9-4cc2-9155-10cfb60defe3.png">

Does anything change for the authentication with the Custom App credentials - as the Private App has been deprecated?

Thanks!

**Comment by IntegralParts** [comment]
I'm running into this same issue trying to set this up in my Github Action. Using custom app credentials doesn't seem to work.

**Comment by driespieters** [comment]
Same problem here.
