### ISSUE TITLE
Migrate this to use shopify cli

### ISSUE THREAD

**Issue by colinbendell** [Shopify/lighthouse-ci-action#4]
The lighthouse ci action should depend on the shopify cli commands instead of themekit

**Comment by anark** [comment]
This would be great(and faster), however I am not seeing a non-interactive way to use shopify-cli.  It looks like shopify-cli requires the user to go through the oauth process manually.  If shopify-cli allowed us to pass an access token then this would be possible.  Do you know if you can login programatically with shopify-cli
