### ISSUE TITLE
Lighthouse CI always redirects to password page on development store

### ISSUE THREAD

**Issue by debolel** [Shopify/lighthouse-ci-action#8]
On development stores (shop password cannot be disabled) lighthouse always redirects to the shop password page and isn't able to test the product/collection pages performance although the `SHOP_PASSWORD` is set in the GitHub secret settings and the `lighthouse-ci.yml` is setup to use it.

This is an issue on themes with the default Shopify or custom password page where the url `/password?password=<pwd>` link is not working (it works with Dawn theme)

<img width="619" alt="Screen Shot 2021-07-07 at 12 19 44 PM" src="https://user-images.githubusercontent.com/31937773/124743050-9f06ca00-df1d-11eb-954a-dae82dc095bf.png">

<img width="526" alt="Screen Shot 2021-07-07 at 12 19 24 PM" src="https://user-images.githubusercontent.com/31937773/124743009-931b0800-df1d-11eb-8218-ed85549a476b.png">

<img width="704" alt="Screen Shot 2021-07-07 at 12 18 53 PM" src="https://user-images.githubusercontent.com/31937773/124742935-80083800-df1d-11eb-8ef4-a89952b78a5f.png">

I have also tried updating the set password on both the shop and GitHub secret without any luck

**Comment by charlespwd** [comment]
Confirmed. I'm investigating.

**Comment by charlespwd** [comment]
Hey @debolel, it should be fixed in the latest 1.0 tag.

I'm assuming that there's a `<form action="/password">` on the page and that within it there's an `<input type=password>`.

Let me know if you still have issues!

**Comment by ai-marion** [comment]
Hello! I just want to bump this issue again. As of today, I'm experiencing this. Is this something specific to my store/theme? Yesterday the results are showing for all "homepage", "collections page", and "product page". Today, it's only the password page like the above. Thanks and I appreciate your help so much!
